/**
 * Generates THIRD-PARTY-NOTICES.md from the production dependency tree.
 *
 * Distributing a packaged app redistributes every bundled dependency, and
 * essentially all of the permissive licences involved (MIT, BSD, Apache-2.0,
 * ISC) require their copyright notice to travel with the binary. MPL-2.0 also
 * requires pointing recipients at the source.
 *
 * Run with: npm run notices
 */

import { promises as fs } from 'node:fs'
import { createHash } from 'node:crypto'
import { execFileSync } from 'node:child_process'
import { join } from 'node:path'

const OUTPUT = 'THIRD-PARTY-NOTICES.md'

/** Names of every package in the production tree, flattened. */
function productionPackages() {
  const raw = execFileSync('npm', ['ls', '--prod', '--all', '--json'], {
    encoding: 'utf8',
    maxBuffer: 64 * 1024 * 1024
  })
  const tree = JSON.parse(raw)
  const names = new Set()
  const walk = (node) => {
    for (const [name, info] of Object.entries(node.dependencies ?? {})) {
      if (names.has(name)) continue
      names.add(name)
      walk(info)
    }
  }
  walk(tree)
  return [...names].sort()
}

const LICENSE_FILENAMES = [
  'LICENSE', 'LICENSE.md', 'LICENSE.txt', 'LICENCE', 'LICENCE.md', 'LICENCE.txt',
  'License', 'License.md', 'license', 'license.md', 'COPYING', 'COPYING.md'
]

async function readPackage(name) {
  const dir = join('node_modules', ...name.split('/'))
  let pkg
  try {
    pkg = JSON.parse(await fs.readFile(join(dir, 'package.json'), 'utf8'))
  } catch {
    // Optional or platform-specific dependency that was never installed, so it
    // is not in the shipped bundle either.
    return null
  }

  let license = pkg.license
  if (license && typeof license === 'object') license = license.type
  if (!license && Array.isArray(pkg.licenses) && pkg.licenses[0]) license = pkg.licenses[0].type

  let text = null
  for (const candidate of LICENSE_FILENAMES) {
    try {
      text = await fs.readFile(join(dir, candidate), 'utf8')
      break
    } catch {
      /* try the next candidate */
    }
  }

  return {
    name,
    version: pkg.version ?? 'unknown',
    license: license ?? 'see notice below',
    repository:
      typeof pkg.repository === 'string' ? pkg.repository : (pkg.repository?.url ?? null),
    text: text?.trim() ?? null
  }
}

const names = productionPackages()
const packages = (await Promise.all(names.map(readPackage))).filter(Boolean)

// Group by identical licence text so a single MIT body is printed once rather
// than 138 times, with the packages it covers listed against it.
const groups = new Map()
for (const pkg of packages) {
  const key = pkg.text ? createHash('sha256').update(pkg.text).digest('hex') : `none:${pkg.license}`
  if (!groups.has(key)) groups.set(key, { license: pkg.license, text: pkg.text, packages: [] })
  groups.get(key).packages.push(pkg)
}

const ordered = [...groups.values()].sort((a, b) => b.packages.length - a.packages.length)

const lines = []
lines.push('# Third-Party Notices')
lines.push('')
lines.push('Torrent Downloader bundles the open-source packages listed here. Each is the')
lines.push('property of its respective authors and is distributed under the licence shown')
lines.push('with it. This file is generated by `npm run notices`.')
lines.push('')
lines.push('It covers the npm dependencies bundled into the application. The Electron')
lines.push('runtime and the Chromium sources it embeds carry their own notices, shipped')
lines.push('alongside the app as `LICENSE.electron.txt` and `LICENSES.chromium.html`.')
lines.push('')
lines.push(`Generated from ${packages.length} production packages.`)
lines.push('')

const summary = new Map()
for (const pkg of packages) summary.set(pkg.license, (summary.get(pkg.license) ?? 0) + 1)
lines.push('## Summary')
lines.push('')
lines.push('| Licence | Packages |')
lines.push('| --- | ---: |')
for (const [license, count] of [...summary.entries()].sort((a, b) => b[1] - a[1])) {
  lines.push(`| ${license} | ${count} |`)
}
lines.push('')

// MPL-2.0 carries an explicit source-availability obligation, so call it out
// rather than burying it in the list.
const mpl = packages.filter((p) => /MPL/i.test(p.license))
if (mpl.length > 0) {
  lines.push('## Source availability (MPL-2.0)')
  lines.push('')
  lines.push('The following packages are covered by the Mozilla Public License 2.0. They are')
  lines.push('included unmodified; their source is available from the locations below and from')
  lines.push('the npm registry.')
  lines.push('')
  for (const pkg of mpl) {
    lines.push(`- **${pkg.name}** ${pkg.version} — ${pkg.repository ?? 'https://www.npmjs.com/package/' + pkg.name}`)
  }
  lines.push('')
}

lines.push('## Licences')
lines.push('')
for (const group of ordered) {
  lines.push(`### ${group.license}`)
  lines.push('')
  for (const pkg of group.packages) lines.push(`- ${pkg.name} ${pkg.version}`)
  lines.push('')
  if (group.text) {
    lines.push('```')
    lines.push(group.text)
    lines.push('```')
  } else {
    lines.push(`_No licence file is distributed with these packages; they declare \`${group.license}\` in package.json._`)
  }
  lines.push('')
}

await fs.writeFile(OUTPUT, lines.join('\n'))
console.log(`${OUTPUT}: ${packages.length} packages, ${ordered.length} distinct licence texts`)
